import type { FieldDef } from '../../ui/form';
import { formatDate, money as formatMoney, options, todayIso, weekStart } from '../../lib/format';
import { StatusBadge } from '../../ui/ui';
import type { RecordConfig } from './Records';

export const select=(name:string,label:string,values:string[]):FieldDef=>({name,label,type:'select',noEmpty:true,options:options(values)});
const title:FieldDef={name:'title',label:'Title',type:'text',required:true,wide:true};
const project:FieldDef={name:'projectId',label:'Project',type:'project'};
const notes:FieldDef={name:'notes',label:'Notes',type:'textarea'};
export const eventConfig:RecordConfig={resource:'events',noun:'event',fields:[title,project,{name:'date',label:'Date',type:'date',required:true},{name:'startTime',label:'Start time (Manila)',type:'time',required:true},{name:'endTime',label:'End time (Manila)',type:'time',required:true},select('kind','Type',['meeting','review','shoot','deadline','internal']),{name:'location',label:'Room or location',type:'text'},{name:'attendees',label:'Attendees',type:'members'},notes],defaults:{date:todayIso(),startTime:'09:00',endTime:'10:00'},columns:[{label:'Event',render:r=>r.title},{label:'Date',render:r=>formatDate(r.date)},{label:'Time',render:r=>`${r.startTime}–${r.endTime}`},{label:'Type',render:r=><StatusBadge value={r.kind}/>},{label:'Location',render:r=>r.location||'—'}]};
export const dealConfig:RecordConfig={resource:'deals',noun:'deal',fields:[title,{name:'clientId',label:'Client',type:'client'},{name:'owner',label:'Owner',type:'member'},{name:'amount',label:'Value (PHP)',type:'money',required:true},select('stage','Stage',['lead','discovery','proposal','negotiation','won','lost']),{name:'nextStep',label:'Next step',type:'textarea'},{name:'dueDate',label:'Follow-up date',type:'date'}],columns:[{label:'Opportunity',render:r=>r.title},{label:'Client',render:r=>r.clientName||'—'},{label:'Value',render:r=>formatMoney(r.amount)},{label:'Stage',render:r=><StatusBadge value={r.stage}/>},{label:'Next step',render:r=>r.nextStep},{label:'Follow up',render:r=>r.dueDate?formatDate(r.dueDate):'—'}]};
export const expenseConfig:RecordConfig={resource:'expenses',noun:'expense',executiveOnly:true,fields:[title,project,{name:'amount',label:'Amount (PHP)',type:'money',required:true},{name:'date',label:'Date',type:'date',required:true},select('category','Category',['payroll','software','office','production','marketing','other']),notes],defaults:{date:todayIso()},columns:[{label:'Expense',render:r=>r.title},{label:'Date',render:r=>formatDate(r.date)},{label:'Category',render:r=>r.category},{label:'Amount',render:r=>formatMoney(r.amount)}]};
export const leaveConfig:RecordConfig={resource:'leave',noun:'leave request',fields:[select('kind','Type',['vacation','sick','personal','half_day']),{name:'startDate',label:'Start date',type:'date',required:true},{name:'endDate',label:'End date',type:'date',required:true},notes],canEdit:(r,me)=>r.createdBy===me&&r.status==='pending',canDelete:()=>false,columns:[{label:'Person',render:r=>r.createdByName||r.createdBy},{label:'Type',render:r=>r.kind.replace('_',' ')},{label:'From',render:r=>formatDate(r.startDate)},{label:'To',render:r=>formatDate(r.endDate)},{label:'Status',render:r=><StatusBadge value={r.status}/>} ]};
export const capacityConfig:RecordConfig={resource:'capacity',noun:'capacity plan',executiveOnly:true,fields:[{name:'member',label:'Person',type:'member',required:true},{name:'weekOf',label:'Week starting Monday',type:'date',required:true},{name:'hours',label:'Planned hours',type:'number',required:true},{name:'available',label:'Available hours',type:'number',required:true}],defaults:{weekOf:weekStart(todayIso()),hours:0,available:40},columns:[{label:'Person',render:r=>r.member},{label:'Week',render:r=>formatDate(r.weekOf)},{label:'Planned',render:r=>`${r.hours} h`},{label:'Available',render:r=>`${r.available} h`},{label:'Utilisation',render:r=><span className={r.hours>r.available?'is-overdue':''}>{Math.round(r.hours/r.available*100)}%</span>}]};
export const handbookConfig:RecordConfig={resource:'handbook',noun:'document',executiveOnly:true,fields:[title,{name:'category',label:'Category',type:'text',required:true},{name:'body',label:'Content',type:'textarea',rows:14,required:true}],defaults:{category:'Studio'},columns:[{label:'Document',render:r=>r.title},{label:'Category',render:r=>r.category},{label:'Updated',render:r=>formatDate(r.updatedAt.slice(0,10))}]};
